### PR TITLE
Added background image toggle

### PR DESCRIPTION
**Pull request by guiszk**
Added a background image toggle, that can be set before playing the game.

### CODE REVIEW

**Review by lemmoor — CHANGES_REQUESTED** [review]
Looks good, but could you make it usable while the game is running? 
Also, I think it should be checked by default. Thanks.

**Comment by guiszk** [comment]
Sure!

**Comment by guiszk** [comment]
I updated the toggle and fixed all conflicts, hopefully everything's working now.

**Comment by lemmoor** [comment]
Yep, looks good, thanks for the PR!

**Pull request merged**
